// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:stt/types@1.0.0" = "golem_stt::golem::stt::types"
//   * with "golem:stt/transcription@1.0.0" = "golem_stt::golem::stt::transcription"
//   * with "golem:stt/languages@1.0.0" = "golem_stt::golem::stt::languages"
//   * generate_unused_types
use golem_stt::golem::stt::types as __with_name0;
use golem_stt::golem::stt::languages as __with_name1;
use golem_stt::golem::stt::transcription as __with_name2;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:golem:stt-whisper@1.0.0:stt-library:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2075] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x99\x0f\x01A\x02\x01\
A\x0b\x01B\x1f\x01m\x03\x07seconds\x08requests\x07credits\x04\0\x0aquota-unit\x03\
\0\0\x01r\x04\x04usedy\x05limity\x0areset-timew\x04unit\x01\x04\0\x0aquota-info\x03\
\0\x02\x01q\x0d\x0dinvalid-audio\x01s\0\x12unsupported-format\x01s\0\x14unsuppor\
ted-language\x01s\0\x14transcription-failed\x01s\0\x0cunauthorized\x01s\0\x0dacc\
ess-denied\x01s\0\x0equota-exceeded\x01\x03\0\x0crate-limited\x01s\0\x14insuffic\
ient-credits\0\0\x15unsupported-operation\x01s\0\x13service-unavailable\x01s\0\x0d\
network-error\x01s\0\x0einternal-error\x01s\0\x04\0\x09stt-error\x03\0\x04\x01s\x04\
\0\x0dlanguage-code\x03\0\x06\x01m\x06\x03wav\x03mp3\x04flac\x03ogg\x03aac\x03pc\
m\x04\0\x0caudio-format\x03\0\x08\x01ky\x01k}\x01r\x03\x06format\x09\x0bsample-r\
ate\x0a\x08channels\x0b\x04\0\x0caudio-config\x03\0\x0c\x01m\x01\x04word\x04\0\x10\
timing-mark-type\x03\0\x0e\x01r\x03\x12start-time-secondsv\x10end-time-secondsv\x09\
mark-type\x0f\x04\0\x0btiming-info\x03\0\x10\x01k\x11\x01kv\x01ks\x01r\x04\x04te\
xts\x0btiming-info\x12\x0aconfidence\x13\x0aspeaker-id\x14\x04\0\x0cword-segment\
\x03\0\x15\x01p\x16\x01r\x03\x04texts\x0aconfidencev\x05words\x17\x04\0\x16trans\
cript-alternative\x03\0\x18\x01r\x05\x10duration-secondsv\x10audio-size-bytesy\x0a\
request-ids\x05model\x14\x08language\x07\x04\0\x16transcription-metadata\x03\0\x1a\
\x01p\x19\x01r\x02\x0calternatives\x1c\x08metadata\x1b\x04\0\x14transcription-re\
sult\x03\0\x1d\x04\0\x15golem:stt/types@1.0.0\x05\0\x02\x03\0\0\x0dlanguage-code\
\x02\x03\0\0\x09stt-error\x01B\x0a\x02\x03\x02\x01\x01\x04\0\x0dlanguage-code\x03\
\0\0\x02\x03\x02\x01\x02\x04\0\x09stt-error\x03\0\x02\x01r\x03\x04code\x01\x04na\
mes\x0bnative-names\x04\0\x0dlanguage-info\x03\0\x04\x01p\x05\x01j\x01\x06\x01\x03\
\x01@\0\0\x07\x04\0\x0elist-languages\x01\x08\x04\0\x19golem:stt/languages@1.0.0\
\x05\x03\x02\x03\0\0\x0caudio-config\x02\x03\0\0\x14transcription-result\x02\x03\
\0\0\x16transcript-alternative\x01B'\x02\x03\x02\x01\x04\x04\0\x0caudio-config\x03\
\0\0\x02\x03\x02\x01\x05\x04\0\x14transcription-result\x03\0\x02\x02\x03\x02\x01\
\x02\x04\0\x09stt-error\x03\0\x04\x02\x03\x02\x01\x01\x04\0\x0dlanguage-code\x03\
\0\x06\x02\x03\x02\x01\x06\x04\0\x16transcript-alternative\x03\0\x08\x01k\x7f\x01\
k\x07\x01ks\x01ps\x01k\x0d\x01r\x08\x11enable-timestamps\x0a\x1aenable-speaker-d\
iarization\x0a\x08language\x0b\x05model\x0c\x10profanity-filter\x0a\x0espeech-co\
ntext\x0e\x16enable-word-confidence\x0a\x14enable-timing-detail\x0a\x04\0\x12tra\
nscribe-options\x03\0\x0f\x04\0\x14transcription-stream\x03\x01\x01h\x11\x01p}\x01\
j\0\x01\x05\x01@\x02\x04self\x12\x05chunk\x13\0\x14\x04\0'[method]transcription-\
stream.send-audio\x01\x15\x01@\x01\x04self\x12\0\x14\x04\0#[method]transcription\
-stream.finish\x01\x16\x01k\x09\x01j\x01\x17\x01\x05\x01@\x01\x04self\x12\0\x18\x04\
\00[method]transcription-stream.receive-alternative\x01\x19\x01@\x01\x04self\x12\
\x01\0\x04\0\"[method]transcription-stream.close\x01\x1a\x01k\x10\x01j\x01\x03\x01\
\x05\x01@\x03\x05audio\x13\x06config\x01\x07options\x1b\0\x1c\x04\0\x0atranscrib\
e\x01\x1d\x01i\x11\x01j\x01\x1e\x01\x05\x01@\x02\x06config\x01\x07options\x1b\0\x1f\
\x04\0\x11transcribe-stream\x01\x20\x04\0\x1dgolem:stt/transcription@1.0.0\x05\x07\
\x04\0#golem:stt-whisper/stt-library@1.0.0\x04\0\x0b\x11\x01\0\x0bstt-library\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.220.1\x10wit-\
bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
