// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:stt/languages@1.0.0" = "golem_stt::golem::stt::languages"
//   * with "golem:stt/types@1.0.0" = "golem_stt::golem::stt::types"
//   * with "golem:stt/transcription@1.0.0" = "golem_stt::golem::stt::transcription"
//   * generate_unused_types
use golem_stt::golem::stt::types as __with_name0;
use golem_stt::golem::stt::languages as __with_name1;
use golem_stt::golem::stt::transcription as __with_name2;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:golem:stt-deepgram@1.0.0:stt-library:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1908] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xf2\x0d\x01A\x02\x01\
A\x0a\x01B\x1c\x01q\x0c\x0dinvalid-audio\x01s\0\x12unsupported-format\x01s\0\x14\
unsupported-language\x01s\0\x14transcription-failed\x01s\0\x0cunauthorized\x01s\0\
\x0daccess-denied\x01s\0\x0crate-limited\x01s\0\x14insufficient-credits\0\0\x15u\
nsupported-operation\x01s\0\x13service-unavailable\x01s\0\x0dnetwork-error\x01s\0\
\x0einternal-error\x01s\0\x04\0\x09stt-error\x03\0\0\x01s\x04\0\x0dlanguage-code\
\x03\0\x02\x01m\x06\x03wav\x03mp3\x04flac\x03ogg\x03aac\x03pcm\x04\0\x0caudio-fo\
rmat\x03\0\x04\x01ky\x01k}\x01r\x03\x06format\x05\x0bsample-rate\x06\x08channels\
\x07\x04\0\x0caudio-config\x03\0\x08\x01r\x02\x12start-time-secondsv\x10end-time\
-secondsv\x04\0\x0btiming-info\x03\0\x0a\x01k\x0b\x01kv\x01ks\x01r\x04\x04texts\x0b\
timing-info\x0c\x0aconfidence\x0d\x0aspeaker-id\x0e\x04\0\x0cword-segment\x03\0\x0f\
\x01r\x05\x10duration-secondsv\x10audio-size-bytesy\x0arequest-ids\x05model\x0e\x08\
language\x03\x04\0\x16transcription-metadata\x03\0\x11\x01p\x10\x01r\x04\x0atran\
scripts\x0btiming-info\x0c\x0aspeaker-id\x0e\x05words\x13\x04\0\x15transcription\
-segment\x03\0\x14\x01p\x15\x01r\x03\x02ids\x0atranscripts\x08segments\x16\x04\0\
\x15transcription-channel\x03\0\x17\x01p\x18\x01r\x02\x13transcript-metadata\x12\
\x08channels\x19\x04\0\x14transcription-result\x03\0\x1a\x04\0\x15golem:stt/type\
s@1.0.0\x05\0\x02\x03\0\0\x0dlanguage-code\x02\x03\0\0\x09stt-error\x01B\x0a\x02\
\x03\x02\x01\x01\x04\0\x0dlanguage-code\x03\0\0\x02\x03\x02\x01\x02\x04\0\x09stt\
-error\x03\0\x02\x01r\x03\x04code\x01\x04names\x0bnative-names\x04\0\x0dlanguage\
-info\x03\0\x04\x01p\x05\x01j\x01\x06\x01\x03\x01@\0\0\x07\x04\0\x0elist-languag\
es\x01\x08\x04\0\x19golem:stt/languages@1.0.0\x05\x03\x02\x03\0\0\x0caudio-confi\
g\x02\x03\0\0\x14transcription-result\x01B'\x02\x03\x02\x01\x04\x04\0\x0caudio-c\
onfig\x03\0\0\x02\x03\x02\x01\x05\x04\0\x14transcription-result\x03\0\x02\x02\x03\
\x02\x01\x02\x04\0\x09stt-error\x03\0\x04\x02\x03\x02\x01\x01\x04\0\x0dlanguage-\
code\x03\0\x06\x01kv\x01r\x02\x05values\x05boost\x08\x04\0\x06phrase\x03\0\x09\x01\
p\x0a\x01r\x01\x07phrases\x0b\x04\0\x0avocabulary\x03\0\x0c\x01k\x7f\x01k\x07\x01\
ks\x01k\x0d\x01ps\x01k\x12\x01r\x09\x11enable-timestamps\x0e\x1aenable-speaker-d\
iarization\x0e\x08language\x0f\x05model\x10\x10profanity-filter\x0e\x0avocabular\
y\x11\x0espeech-context\x13\x16enable-word-confidence\x0e\x14enable-timing-detai\
l\x0e\x04\0\x12transcribe-options\x03\0\x14\x01p}\x01k\x15\x01r\x04\x0arequest-i\
ds\x05audio\x16\x06config\x01\x07options\x17\x04\0\x15transcription-request\x03\0\
\x18\x01r\x02\x0arequest-ids\x05error\x05\x04\0\x14failed-transcription\x03\0\x1a\
\x01p\x03\x01p\x1b\x01r\x02\x09successes\x1c\x08failures\x1d\x04\0\x1amulti-tran\
scription-result\x03\0\x1e\x01j\x01\x03\x01\x05\x01@\x01\x07request\x19\0\x20\x04\
\0\x0atranscribe\x01!\x01p\x19\x01j\x01\x1f\x01\x05\x01@\x01\x08requests\"\0#\x04\
\0\x0ftranscribe-many\x01$\x04\0\x1dgolem:stt/transcription@1.0.0\x05\x06\x04\0$\
golem:stt-deepgram/stt-library@1.0.0\x04\0\x0b\x11\x01\0\x0bstt-library\x03\0\0\0\
G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.220.1\x10wit-bindge\
n-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
