# yaml-language-server: $schema=https://json.schemastore.org/cargo-make
[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = ["build-whisper", "build-deepgram"] }

[tasks.build-portable]
run_task = { name = ["build-whisper-portable", "build-deepgram-portable"] }

[tasks.release-build]
run_task = { name = ["release-build-whisper", "release-build-deepgram"] }

[tasks.release-build-portable]
run_task = { name = [
    "release-build-whisper-portable",
    "release-build-deepgram-portable",
] }

[tasks.build-whisper]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-whisper"]


[tasks.build-whisper-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-whisper", "--no-default-features"]


[tasks.build-deepgram]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-deepgram"]

[tasks.build-deepgram-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-deepgram", "--no-default-features"]

[tasks.release-build-whisper]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-whisper", "--release"]

[tasks.release-build-whisper-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = [
    "build",
    "-p",
    "golem-stt-whisper",
    "--release",
    "--no-default-features",
]

[tasks.release-build-deepgram]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-stt-deepgram", "--release"]

[tasks.release-build-deepgram-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = [
    "build",
    "-p",
    "golem-stt-deepgram",
    "--release",
    "--no-default-features",
]

[tasks.wit-update]
install_crate = { crate_name = "wit-deps-cli" }
command = "wit-deps"
args = ["update"]

[tasks.wit]
dependencies = ["wit-update"]

script_runner = "@duckscript"
script = """
modules = array aws whisper deepgram

for module in ${modules}
    rm -r ${module}/wit/deps
    mkdir ${module}/wit/deps/golem-stt
    cp wit/golem-stt.wit ${module}/wit/deps/golem-stt/golem-stt.wit
    cp wit/deps/wasi:io ${module}/wit/deps

    echo "Copied WIT for module stt::${module}"
end

# Copy WIT files for integration tests
rm -r ../test-stt/wit/deps/golem-stt
mkdir ../test-stt/wit/deps/golem-stt
mkdir ../test-stt/wit/deps/io
cp wit/golem-stt.wit ../test-stt/wit/deps/golem-stt/golem-stt.wit
cp wit/deps/wasi:io/error.wit ../test-stt/wit/deps/io/error.wit
cp wit/deps/wasi:io/poll.wit ../test-stt/wit/deps/io/poll.wit
cp wit/deps/wasi:io/streams.wit ../test-stt/wit/deps/io/streams.wit
cp wit/deps/wasi:io/world.wit ../test-stt/wit/deps/io/world.wit

echo "Copied WIT for module test"
"""

[tasks.build-test-components]
dependencies = ["build"]
install_crate = "cargo-binstall"
description = "Builds stt test components with golem-cli"
script = '''
cargo-binstall golem-cli@1.2.5 --locked --no-confirm
cargo-binstall wac-cli --locked --no-confirm
cd ../test-stt

golem-cli --version
golem-cli app clean
golem-cli app build -b whisper-debug
'''
