// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:web-search/web-search@1.0.0" = "golem_websearch::golem::websearch::websearch"
//   * with "golem:web-search/types@1.0.0" = "golem_websearch::golem::websearch::types"
//   * generate_unused_types
use golem_websearch::golem::websearch::types as __with_name0;
use golem_websearch::golem::websearch::websearch as __with_name1;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:golem:web-search-google@1.0.0:websearch-library:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1389] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe5\x09\x01A\x02\x01\
A\x08\x01B\x1c\x01ks\x01r\x02\x03urls\x0bdescription\0\x04\0\x0cimage-result\x03\
\0\x01\x01ku\x01p\x02\x01k\x04\x01ps\x01k\x06\x01r\x0a\x05titles\x03urls\x07snip\
pets\x0bdisplay-url\0\x06source\0\x05score\x03\x0chtml-snippet\0\x0edate-publish\
ed\0\x06images\x05\x0econtent-chunks\x07\x04\0\x0dsearch-result\x03\0\x08\x01m\x03\
\x03off\x06medium\x04high\x04\0\x11safe-search-level\x03\0\x0a\x01r\x03\x05limit\
y\x09remainingy\x0freset-timestampw\x04\0\x0frate-limit-info\x03\0\x0c\x01kw\x01\
k\x0b\x01k\x0d\x01r\x09\x05querys\x0dtotal-results\x0e\x0esearch-time-ms\x03\x0b\
safe-search\x0f\x08language\0\x06region\0\x0fnext-page-token\0\x0brate-limits\x10\
\x0ccurrent-pagey\x04\0\x0fsearch-metadata\x03\0\x11\x01m\x04\x03day\x04week\x05\
month\x04year\x04\0\x0atime-range\x03\0\x13\x01ky\x01k\x14\x01k\x7f\x01r\x0b\x05\
querys\x0bsafe-search\x0f\x08language\0\x06region\0\x0bmax-results\x15\x0atime-r\
ange\x16\x0finclude-domains\x07\x0fexclude-domains\x07\x0einclude-images\x17\x0c\
include-html\x17\x0fadvanced-answer\x17\x04\0\x0dsearch-params\x03\0\x18\x01q\x04\
\x0dinvalid-query\0\0\x0crate-limited\x01y\0\x13unsupported-feature\x01s\0\x0dba\
ckend-error\x01s\0\x04\0\x0csearch-error\x03\0\x1a\x04\0\x1cgolem:web-search/typ\
es@1.0.0\x05\0\x02\x03\0\0\x0dsearch-params\x02\x03\0\0\x0dsearch-result\x02\x03\
\0\0\x0fsearch-metadata\x02\x03\0\0\x0csearch-error\x01B\x19\x02\x03\x02\x01\x01\
\x04\0\x0dsearch-params\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0dsearch-result\x03\0\
\x02\x02\x03\x02\x01\x03\x04\0\x0fsearch-metadata\x03\0\x04\x02\x03\x02\x01\x04\x04\
\0\x0csearch-error\x03\0\x06\x04\0\x0esearch-session\x03\x01\x01h\x08\x01p\x03\x01\
j\x01\x0a\x01\x07\x01@\x01\x04self\x09\0\x0b\x04\0\x20[method]search-session.nex\
t-page\x01\x0c\x01k\x05\x01@\x01\x04self\x09\0\x0d\x04\0#[method]search-session.\
get-metadata\x01\x0e\x01i\x08\x01j\x01\x0f\x01\x07\x01@\x01\x06params\x01\0\x10\x04\
\0\x0cstart-search\x01\x11\x01o\x02\x0a\x0d\x01j\x01\x12\x01\x07\x01@\x01\x06par\
ams\x01\0\x13\x04\0\x0bsearch-once\x01\x14\x04\0!golem:web-search/web-search@1.0\
.0\x05\x05\x04\0/golem:web-search-google/websearch-library@1.0.0\x04\0\x0b\x17\x01\
\0\x11websearch-library\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-c\
omponent\x070.220.1\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
